STATUS_NEW = 'new'
STATUS_QUEUED = 'queued'
STATUS_PROCESSING = 'processing'
STATUS_CLASSIFIED = 'classified'
STATUS_QUEUE_FAILED = 'queue_failed'
STATUS_VALIDATION_FAILED = 'validation_failed'
STATUS_LLM_FAILED = 'llm_failed'

FINAL_STATUSES = {
    STATUS_CLASSIFIED,
    STATUS_VALIDATION_FAILED,
    STATUS_LLM_FAILED,
}

REQUEUE_STATUSES = {
    STATUS_QUEUE_FAILED,
    STATUS_LLM_FAILED,
}
